"""add_class_status_field

Revision ID: 0c74c2161c9d
Revises: d256376a7717
Create Date: 2025-12-22 02:03:05.535162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c74c2161c9d'
down_revision: Union[str, Sequence[str], None] = 'd256376a7717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column with server_default for existing records
    op.add_column('classes', sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='classstatus', native_enum=False), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'status')
    # ### end Alembic commands ###
