"""add_stripe_product_price_ids_to_classes

Revision ID: 1998a6839162
Revises: 4427c67644ad
Create Date: 2025-12-11 10:46:20.387817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1998a6839162'
down_revision: Union[str, Sequence[str], None] = '4427c67644ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('stripe_product_id', sa.String(length=255), nullable=True))
    op.add_column('classes', sa.Column('stripe_monthly_price_id', sa.String(length=255), nullable=True))
    op.add_column('classes', sa.Column('stripe_quarterly_price_id', sa.String(length=255), nullable=True))
    op.add_column('classes', sa.Column('stripe_annual_price_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_classes_stripe_product_id'), 'classes', ['stripe_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_stripe_product_id'), table_name='classes')
    op.drop_column('classes', 'stripe_annual_price_id')
    op.drop_column('classes', 'stripe_quarterly_price_id')
    op.drop_column('classes', 'stripe_monthly_price_id')
    op.drop_column('classes', 'stripe_product_id')
    # ### end Alembic commands ###
