"""Add engagement platform features: announcements, attendance, events, photos, badges, checkins

Revision ID: 1dd8afcf7e89
Revises: 1dda0d1f48d9
Create Date: 2025-11-25 18:37:55.042137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd8afcf7e89'
down_revision: Union[str, Sequence[str], None] = '1dda0d1f48d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ATTENDANCE', 'ACHIEVEMENT', 'SKILL', 'MILESTONE', name='badgecategory'), nullable=False),
    sa.Column('criteria', sa.Enum('PERFECT_ATTENDANCE_5', 'PERFECT_ATTENDANCE_10', 'PERFECT_ATTENDANCE_20', 'EARLY_BIRD', 'PUNCTUALITY_KING', 'FIRST_CLASS', 'FIRST_MONTH', 'FIRST_SEASON', 'FIRST_GOAL', 'HAT_TRICK', 'TEAM_PLAYER', 'GOAL_MACHINE', 'ASSIST_MASTER', 'DEFENSIVE_WALL', 'SPEEDSTER', 'ENDURANCE', 'SKILLS_MASTER', 'LEADERSHIP', name='badgecriteria'), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria'),
    sa.UniqueConstraint('name')
    )
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'IMPORTANT', 'URGENT', name='announcementtype'), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_author_id'), 'announcements', ['author_id'], unique=False)
    op.create_table('announcement_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('announcement_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'IMAGE', name='attachmenttype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_attachments_announcement_id'), 'announcement_attachments', ['announcement_id'], unique=False)
    op.create_table('announcement_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('announcement_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'class_id', name='unique_announcement_class')
    )
    op.create_index(op.f('ix_announcement_targets_announcement_id'), 'announcement_targets', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_targets_class_id'), 'announcement_targets', ['class_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('TOURNAMENT', 'MATCH', 'TRAINING', 'WORKSHOP', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_class_id'), 'events', ['class_id'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_table('photo_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='unique_class_category')
    )
    op.create_index(op.f('ix_photo_categories_class_id'), 'photo_categories', ['class_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('marked_by', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'class_id', 'date', name='unique_enrollment_class_date_attendance')
    )
    op.create_index('idx_attendance_date_enrollment', 'attendances', ['enrollment_id', 'date'], unique=False)
    op.create_index(op.f('ix_attendances_class_id'), 'attendances', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_enrollment_id'), 'attendances', ['enrollment_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'class_id', 'check_in_date', name='unique_checkin_per_date')
    )
    op.create_index(op.f('ix_checkins_check_in_date'), 'checkins', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_checkins_class_id'), 'checkins', ['class_id'], unique=False)
    op.create_index(op.f('ix_checkins_enrollment_id'), 'checkins', ['enrollment_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['photo_categories.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_category_id'), 'photos', ['category_id'], unique=False)
    op.create_index(op.f('ix_photos_class_id'), 'photos', ['class_id'], unique=False)
    op.create_table('student_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('awarded_by', sa.String(length=36), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'badge_id', name='unique_student_badge')
    )
    op.create_index(op.f('ix_student_badges_badge_id'), 'student_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_student_badges_enrollment_id'), 'student_badges', ['enrollment_id'], unique=False)
    op.add_column('children', sa.Column('additional_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'additional_notes')
    op.drop_index(op.f('ix_student_badges_enrollment_id'), table_name='student_badges')
    op.drop_index(op.f('ix_student_badges_badge_id'), table_name='student_badges')
    op.drop_table('student_badges')
    op.drop_index(op.f('ix_photos_class_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_category_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_checkins_enrollment_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_class_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_check_in_date'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_attendances_enrollment_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_class_id'), table_name='attendances')
    op.drop_index('idx_attendance_date_enrollment', table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_photo_categories_class_id'), table_name='photo_categories')
    op.drop_table('photo_categories')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_class_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_announcement_targets_class_id'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_announcement_id'), table_name='announcement_targets')
    op.drop_table('announcement_targets')
    op.drop_index(op.f('ix_announcement_attachments_announcement_id'), table_name='announcement_attachments')
    op.drop_table('announcement_attachments')
    op.drop_index(op.f('ix_announcements_author_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_table('badges')
    # ### end Alembic commands ###
