"""add waitlist paymet fields for enrollments

Revision ID: 242aafb787d2
Revises: afe93c2cf1a1
Create Date: 2025-11-30 03:12:15.010414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242aafb787d2'
down_revision: Union[str, Sequence[str], None] = 'afe93c2cf1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('waitlist_payment_method_id', sa.String(length=255), nullable=True))
    op.add_column('enrollments', sa.Column('waitlist_order_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_enrollments_claim_expires'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_waitlist_priority'), table_name='enrollments')
    op.create_index(op.f('ix_enrollments_waitlist_priority'), 'enrollments', ['waitlist_priority'], unique=False)
    op.create_index(op.f('ix_enrollments_claim_window_expires_at'), 'enrollments', ['claim_window_expires_at'], unique=False)
    op.create_index(op.f('ix_enrollments_waitlist_order_id'), 'enrollments', ['waitlist_order_id'], unique=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_unique_constraint(None, 'organizations', ['name'])
    op.create_index(op.f('ix_payments_refund_approved_by_id'), 'payments', ['refund_approved_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_refund_approved_by_id'), table_name='payments')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.alter_column('organizations', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organizations', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_enrollments_waitlist_order_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_claim_window_expires_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_waitlist_priority'), table_name='enrollments')
    op.create_index(op.f('ix_enrollments_waitlist_priority'), 'enrollments', ['waitlist_priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_enrollments_claim_expires'), 'enrollments', ['claim_window_expires_at'], unique=False)
    op.drop_column('enrollments', 'waitlist_order_id')
    op.drop_column('enrollments', 'waitlist_payment_method_id')
    # ### end Alembic commands ###
