"""fix_class_type_enum_values

Revision ID: 32af0f6f3f05
Revises: d4f6348fa314
Create Date: 2025-12-14 02:55:07.838845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32af0f6f3f05'
down_revision: Union[str, Sequence[str], None] = 'd4f6348fa314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - ensure enum uses values instead of names."""
    # No changes needed to database - the enum values are correct
    # The fix is in the SQLAlchemy model configuration
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
