"""add_subscription_billing_fields_to_classes_and_enrollments

Revision ID: 4427c67644ad
Revises: c24f39897f4b
Create Date: 2025-12-11 01:22:01.818753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4427c67644ad'
down_revision: Union[str, Sequence[str], None] = 'c24f39897f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the BillingModel ENUM type first
    billing_model_enum = sa.Enum('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='billingmodel')
    billing_model_enum.create(op.get_bind(), checkfirst=True)

    # Add billing model with default value for existing rows
    op.add_column('classes', sa.Column('billing_model', billing_model_enum, server_default='ONE_TIME', nullable=False))
    op.add_column('classes', sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('classes', sa.Column('quarterly_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('classes', sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('enrollments', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('enrollments', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('enrollments', sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrollments', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrollments', sa.Column('subscription_cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrollments', sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_enrollments_stripe_subscription_id'), 'enrollments', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_stripe_subscription_id'), table_name='enrollments')
    op.drop_column('enrollments', 'cancel_at_period_end')
    op.drop_column('enrollments', 'subscription_cancelled_at')
    op.drop_column('enrollments', 'current_period_end')
    op.drop_column('enrollments', 'current_period_start')
    op.drop_column('enrollments', 'subscription_status')
    op.drop_column('enrollments', 'stripe_subscription_id')
    op.drop_column('classes', 'annual_price')
    op.drop_column('classes', 'quarterly_price')
    op.drop_column('classes', 'monthly_price')
    op.drop_column('classes', 'billing_model')

    # Drop the BillingModel ENUM type
    billing_model_enum = sa.Enum('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='billingmodel')
    billing_model_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
