"""add_children_emergency_contacts_waivers

Revision ID: 8987aa9d559d
Revises: e140a2f5a724
Create Date: 2025-11-24 14:48:05.165086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8987aa9d559d'
down_revision: Union[str, Sequence[str], None] = 'e140a2f5a724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('jersey_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='jerseysize'), nullable=True),
    sa.Column('grade', sa.Enum('PRE_K', 'KINDERGARTEN', 'GRADE_1', 'GRADE_2', 'GRADE_3', 'GRADE_4', 'GRADE_5', 'GRADE_6', 'GRADE_7', 'GRADE_8', 'GRADE_9', 'GRADE_10', 'GRADE_11', 'GRADE_12', name='grade'), nullable=True),
    sa.Column('medical_conditions_encrypted', sa.Text(), nullable=True),
    sa.Column('has_no_medical_conditions', sa.Boolean(), nullable=False),
    sa.Column('after_school_attendance', sa.Boolean(), nullable=False),
    sa.Column('after_school_program', sa.String(length=200), nullable=True),
    sa.Column('health_insurance_number_encrypted', sa.String(length=500), nullable=True),
    sa.Column('how_heard_about_us', sa.Enum('FRIEND', 'SOCIAL_MEDIA', 'SCHOOL', 'FLYER', 'GOOGLE', 'OTHER', name='howheardaboutus'), nullable=True),
    sa.Column('how_heard_other_text', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_user_id'), 'children', ['user_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiver_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('waiver_type', sa.Enum('MEDICAL_RELEASE', 'LIABILITY', 'PHOTO_RELEASE', 'CANCELLATION_POLICY', name='waivertype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('applies_to_program_id', sa.String(length=36), nullable=True),
    sa.Column('applies_to_school_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applies_to_program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['applies_to_school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiver_acceptances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('waiver_template_id', sa.String(length=36), nullable=False),
    sa.Column('waiver_version', sa.Integer(), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_ip', sa.String(length=45), nullable=False),
    sa.Column('signer_user_agent', sa.String(length=500), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waiver_template_id'], ['waiver_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_acceptances_user_id'), 'waiver_acceptances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiver_acceptances_user_id'), table_name='waiver_acceptances')
    op.drop_table('waiver_acceptances')
    op.drop_table('waiver_templates')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_children_user_id'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
