"""add binary data fields to photos

Revision ID: c24f39897f4b
Revises: 0ca1bc188151
Create Date: 2025-12-07 20:39:13.135772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24f39897f4b'
down_revision: Union[str, Sequence[str], None] = '0ca1bc188151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('photos', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('photos', sa.Column('thumbnail_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'thumbnail_data')
    op.drop_column('photos', 'content_type')
    op.drop_column('photos', 'file_data')
    # ### end Alembic commands ###
