"""add_foreign_key_to_coach_id

Revision ID: c84dedd02c57
Revises: payment_options_001
Create Date: 2025-12-17 17:03:09.667562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84dedd02c57'
down_revision: Union[str, Sequence[str], None] = 'payment_options_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add foreign key constraint for coach_id -> users.id
    op.create_foreign_key('fk_classes_coach_id_users', 'classes', 'users', ['coach_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint for coach_id
    op.drop_constraint('fk_classes_coach_id_users', 'classes', type_='foreignkey')
    # ### end Alembic commands ###
