"""make weekdays and times optional for classes

Revision ID: d052e0ff4202
Revises: 8e7435a4fb99
Create Date: 2025-11-26 22:08:12.083725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd052e0ff4202'
down_revision: Union[str, Sequence[str], None] = '8e7435a4fb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'weekdays',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('classes', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('classes', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('classes', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('classes', 'weekdays',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
