"""Initial_migrations001 fresh_tables

Revision ID: d256376a7717
Revises: 
Create Date: 2025-12-20 16:03:08.442394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd256376a7717'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_areas_is_deleted'), 'areas', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_areas_organization_id'), 'areas', ['organization_id'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ATTENDANCE', 'ACHIEVEMENT', 'SKILL', 'MILESTONE', name='badgecategory'), nullable=False),
    sa.Column('criteria', sa.Enum('PERFECT_ATTENDANCE_5', 'PERFECT_ATTENDANCE_10', 'PERFECT_ATTENDANCE_20', 'EARLY_BIRD', 'PUNCTUALITY_KING', 'FIRST_CLASS', 'FIRST_MONTH', 'FIRST_SEASON', 'FIRST_GOAL', 'HAT_TRICK', 'TEAM_PLAYER', 'GOAL_MACHINE', 'ASSIST_MASTER', 'DEFENSIVE_WALL', 'SPEEDSTER', 'ENDURANCE', 'SKILLS_MASTER', 'LEADERSHIP', name='badgecriteria'), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_is_deleted'), 'badges', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_badges_organization_id'), 'badges', ['organization_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_programs_is_deleted'), 'programs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_programs_organization_id'), 'programs', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'coach', 'parent', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('account_credit', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index('ix_users_organization_email', 'users', ['organization_id', 'email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'IMPORTANT', 'URGENT', name='announcementtype'), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_author_id'), 'announcements', ['author_id'], unique=False)
    op.create_index(op.f('ix_announcements_is_deleted'), 'announcements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_announcements_organization_id'), 'announcements', ['organization_id'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('jersey_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='jerseysize', native_enum=False), nullable=True),
    sa.Column('grade', sa.Enum('PRE_K', 'KINDERGARTEN', 'GRADE_1', 'GRADE_2', 'GRADE_3', 'GRADE_4', 'GRADE_5', 'GRADE_6', 'GRADE_7', 'GRADE_8', 'GRADE_9', 'GRADE_10', 'GRADE_11', 'GRADE_12', name='grade', native_enum=False), nullable=True),
    sa.Column('medical_conditions_encrypted', sa.Text(), nullable=True),
    sa.Column('has_no_medical_conditions', sa.Boolean(), nullable=False),
    sa.Column('has_medical_alert', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('after_school_attendance', sa.Boolean(), nullable=False),
    sa.Column('after_school_program', sa.String(length=200), nullable=True),
    sa.Column('health_insurance_number_encrypted', sa.String(length=500), nullable=True),
    sa.Column('how_heard_about_us', sa.Enum('FRIEND', 'SOCIAL_MEDIA', 'SCHOOL', 'FLYER', 'GOOGLE', 'OTHER', name='howheardaboutus', native_enum=False), nullable=True),
    sa.Column('how_heard_other_text', sa.String(length=200), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_is_deleted'), 'children', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_children_organization_id'), 'children', ['organization_id'], unique=False)
    op.create_index(op.f('ix_children_user_id'), 'children', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'PAID', 'PARTIALLY_PAID', 'REFUNDED', 'CANCELLED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_is_deleted'), 'orders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_orders_organization_id'), 'orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_orders_stripe_payment_intent_id'), 'orders', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_is_deleted'), 'password_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_password_history_organization_id'), 'password_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_organization_id'), 'password_reset_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_area_id'), 'schools', ['area_id'], unique=False)
    op.create_index(op.f('ix_schools_is_deleted'), 'schools', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_schools_organization_id'), 'schools', ['organization_id'], unique=False)
    op.create_table('announcement_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('announcement_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'IMAGE', name='attachmenttype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_attachments_announcement_id'), 'announcement_attachments', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_attachments_is_deleted'), 'announcement_attachments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_announcement_attachments_organization_id'), 'announcement_attachments', ['organization_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ledger_code', sa.String(length=50), nullable=True),
    sa.Column('school_code', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('website_link', sa.String(length=500), nullable=True),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('coach_id', sa.String(length=36), nullable=True),
    sa.Column('class_type', sa.Enum('short_term', 'membership', 'one-time', name='classtype', native_enum=False), nullable=False),
    sa.Column('weekdays', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('registration_start_date', sa.Date(), nullable=True),
    sa.Column('registration_end_date', sa.Date(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=20), nullable=True),
    sa.Column('repeat_every_weeks', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_enrollment', sa.Integer(), nullable=False),
    sa.Column('waitlist_enabled', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('membership_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('installments_enabled', sa.Boolean(), nullable=False),
    sa.Column('billing_model', sa.Enum('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='billingmodel', native_enum=False), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quarterly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_options', sa.JSON(), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_monthly_price_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_quarterly_price_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_annual_price_id', sa.String(length=255), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_area_id'), 'classes', ['area_id'], unique=False)
    op.create_index(op.f('ix_classes_coach_id'), 'classes', ['coach_id'], unique=False)
    op.create_index(op.f('ix_classes_is_deleted'), 'classes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_classes_organization_id'), 'classes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_classes_program_id'), 'classes', ['program_id'], unique=False)
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_index(op.f('ix_classes_stripe_product_id'), 'classes', ['stripe_product_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_child_id'), 'emergency_contacts', ['child_id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_is_deleted'), 'emergency_contacts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_organization_id'), 'emergency_contacts', ['organization_id'], unique=False)
    op.create_table('installment_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_installments', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='installmentfrequency', native_enum=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'DEFAULTED', name='installmentplanstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_plans_is_deleted'), 'installment_plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_installment_plans_order_id'), 'installment_plans', ['order_id'], unique=False)
    op.create_index(op.f('ix_installment_plans_organization_id'), 'installment_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_installment_plans_user_id'), 'installment_plans', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('payment_type', sa.Enum('ONE_TIME', 'SUBSCRIPTION', 'INSTALLMENT', name='paymenttype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_status', sa.Enum('NOT_REQUESTED', 'PENDING', 'APPROVED', 'REJECTED', name='refundstatus', native_enum=False), nullable=False),
    sa.Column('refund_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('refund_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_rejection_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['refund_approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_is_deleted'), 'payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payments_next_retry_at'), 'payments', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_refund_approved_by_id'), 'payments', ['refund_approved_by_id'], unique=False)
    op.create_index(op.f('ix_payments_refund_status'), 'payments', ['refund_status'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('waiver_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('waiver_type', sa.Enum('MEDICAL_RELEASE', 'LIABILITY', 'PHOTO_RELEASE', 'CANCELLATION_POLICY', name='waivertype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('applies_to_program_id', sa.String(length=36), nullable=True),
    sa.Column('applies_to_school_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['applies_to_program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['applies_to_school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_templates_applies_to_program_id'), 'waiver_templates', ['applies_to_program_id'], unique=False)
    op.create_index(op.f('ix_waiver_templates_applies_to_school_id'), 'waiver_templates', ['applies_to_school_id'], unique=False)
    op.create_index(op.f('ix_waiver_templates_is_deleted'), 'waiver_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_waiver_templates_organization_id'), 'waiver_templates', ['organization_id'], unique=False)
    op.create_table('announcement_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('announcement_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'class_id', name='unique_announcement_class')
    )
    op.create_index(op.f('ix_announcement_targets_announcement_id'), 'announcement_targets', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_targets_class_id'), 'announcement_targets', ['class_id'], unique=False)
    op.create_index(op.f('ix_announcement_targets_is_deleted'), 'announcement_targets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_announcement_targets_organization_id'), 'announcement_targets', ['organization_id'], unique=False)
    op.create_table('discount_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('applies_to_program_id', sa.String(length=36), nullable=True),
    sa.Column('applies_to_class_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['applies_to_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['applies_to_program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_discount_codes_organization_code')
    )
    op.create_index(op.f('ix_discount_codes_applies_to_class_id'), 'discount_codes', ['applies_to_class_id'], unique=False)
    op.create_index(op.f('ix_discount_codes_applies_to_program_id'), 'discount_codes', ['applies_to_program_id'], unique=False)
    op.create_index(op.f('ix_discount_codes_created_by_id'), 'discount_codes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_discount_codes_is_deleted'), 'discount_codes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_discount_codes_organization_id'), 'discount_codes', ['organization_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELLED', 'COMPLETED', 'WAITLISTED', name='enrollmentstatus'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('waitlist_priority', sa.String(length=20), nullable=True),
    sa.Column('auto_promote', sa.Boolean(), nullable=False),
    sa.Column('claim_window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waitlist_payment_method_id', sa.String(length=255), nullable=True),
    sa.Column('waitlist_order_id', sa.String(length=36), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'child_id', 'class_id', name='uq_enrollment_child_class_organization')
    )
    op.create_index(op.f('ix_enrollments_child_id'), 'enrollments', ['child_id'], unique=False)
    op.create_index(op.f('ix_enrollments_claim_window_expires_at'), 'enrollments', ['claim_window_expires_at'], unique=False)
    op.create_index(op.f('ix_enrollments_class_id'), 'enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_enrollments_is_deleted'), 'enrollments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_enrollments_organization_id'), 'enrollments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_enrollments_stripe_subscription_id'), 'enrollments', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_index(op.f('ix_enrollments_waitlist_order_id'), 'enrollments', ['waitlist_order_id'], unique=False)
    op.create_index(op.f('ix_enrollments_waitlist_priority'), 'enrollments', ['waitlist_priority'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('TOURNAMENT', 'MATCH', 'TRAINING', 'WORKSHOP', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_class_id'), 'events', ['class_id'], unique=False)
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_table('installment_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('installment_plan_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'SKIPPED', name='installmentpaymentstatus', native_enum=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['installment_plan_id'], ['installment_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_payments_installment_plan_id'), 'installment_payments', ['installment_plan_id'], unique=False)
    op.create_index(op.f('ix_installment_payments_is_deleted'), 'installment_payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_installment_payments_organization_id'), 'installment_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_installment_payments_payment_id'), 'installment_payments', ['payment_id'], unique=False)
    op.create_table('photo_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'class_id', 'name', name='uq_photo_categories_organization_class_name')
    )
    op.create_index(op.f('ix_photo_categories_class_id'), 'photo_categories', ['class_id'], unique=False)
    op.create_index(op.f('ix_photo_categories_is_deleted'), 'photo_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_photo_categories_organization_id'), 'photo_categories', ['organization_id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=True),
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('scholarship_type', sa.String(length=100), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_approved_by_id'), 'scholarships', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_scholarships_child_id'), 'scholarships', ['child_id'], unique=False)
    op.create_index(op.f('ix_scholarships_class_id'), 'scholarships', ['class_id'], unique=False)
    op.create_index(op.f('ix_scholarships_is_deleted'), 'scholarships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_scholarships_organization_id'), 'scholarships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scholarships_user_id'), 'scholarships', ['user_id'], unique=False)
    op.create_table('waiver_acceptances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('waiver_template_id', sa.String(length=36), nullable=False),
    sa.Column('waiver_version', sa.Integer(), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_ip', sa.String(length=45), nullable=False),
    sa.Column('signer_user_agent', sa.String(length=500), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waiver_template_id'], ['waiver_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_acceptances_is_deleted'), 'waiver_acceptances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_waiver_acceptances_organization_id'), 'waiver_acceptances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_waiver_acceptances_user_id'), 'waiver_acceptances', ['user_id'], unique=False)
    op.create_index(op.f('ix_waiver_acceptances_waiver_template_id'), 'waiver_acceptances', ['waiver_template_id'], unique=False)
    op.create_table('account_credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('EARNED', 'SPENT', 'EXPIRED', 'REFUND_TO_CREDIT', 'TRANSFER_DOWNGRADE', name='credittransactiontype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_credit_transactions_created_at', 'account_credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_credit_transactions_user_id'), 'account_credit_transactions', ['user_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', name='attendancestatus', native_enum=False), nullable=False),
    sa.Column('marked_by', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'class_id', 'date', name='unique_enrollment_class_date_attendance')
    )
    op.create_index('idx_attendance_date_enrollment', 'attendances', ['enrollment_id', 'date'], unique=False)
    op.create_index(op.f('ix_attendances_class_id'), 'attendances', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_enrollment_id'), 'attendances', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_attendances_is_deleted'), 'attendances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendances_marked_by'), 'attendances', ['marked_by'], unique=False)
    op.create_index(op.f('ix_attendances_organization_id'), 'attendances', ['organization_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'class_id', 'check_in_date', name='unique_checkin_per_date')
    )
    op.create_index(op.f('ix_checkins_check_in_date'), 'checkins', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_checkins_class_id'), 'checkins', ['class_id'], unique=False)
    op.create_index(op.f('ix_checkins_enrollment_id'), 'checkins', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_checkins_is_deleted'), 'checkins', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_checkins_organization_id'), 'checkins', ['organization_id'], unique=False)
    op.create_table('discount_code_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discount_code_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_code_id', 'user_id', 'class_id', name='uq_discount_code_usage_user_class')
    )
    op.create_index(op.f('ix_discount_code_usage_class_id'), 'discount_code_usage', ['class_id'], unique=False)
    op.create_index(op.f('ix_discount_code_usage_discount_code_id'), 'discount_code_usage', ['discount_code_id'], unique=False)
    op.create_index(op.f('ix_discount_code_usage_user_id'), 'discount_code_usage', ['user_id'], unique=False)
    op.create_table('order_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('discount_code_id', sa.String(length=36), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_description', sa.String(length=200), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_line_items_discount_code_id'), 'order_line_items', ['discount_code_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_enrollment_id'), 'order_line_items', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_is_deleted'), 'order_line_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_order_line_items_order_id'), 'order_line_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_organization_id'), 'order_line_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_stripe_price_id'), 'order_line_items', ['stripe_price_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_data', sa.LargeBinary(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['photo_categories.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_category_id'), 'photos', ['category_id'], unique=False)
    op.create_index(op.f('ix_photos_class_id'), 'photos', ['class_id'], unique=False)
    op.create_index(op.f('ix_photos_is_deleted'), 'photos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_photos_organization_id'), 'photos', ['organization_id'], unique=False)
    op.create_index(op.f('ix_photos_uploaded_by'), 'photos', ['uploaded_by'], unique=False)
    op.create_table('student_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('awarded_by', sa.String(length=36), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'badge_id', name='unique_student_badge')
    )
    op.create_index(op.f('ix_student_badges_awarded_by'), 'student_badges', ['awarded_by'], unique=False)
    op.create_index(op.f('ix_student_badges_badge_id'), 'student_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_student_badges_enrollment_id'), 'student_badges', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_student_badges_is_deleted'), 'student_badges', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_student_badges_organization_id'), 'student_badges', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_badges_organization_id'), table_name='student_badges')
    op.drop_index(op.f('ix_student_badges_is_deleted'), table_name='student_badges')
    op.drop_index(op.f('ix_student_badges_enrollment_id'), table_name='student_badges')
    op.drop_index(op.f('ix_student_badges_badge_id'), table_name='student_badges')
    op.drop_index(op.f('ix_student_badges_awarded_by'), table_name='student_badges')
    op.drop_table('student_badges')
    op.drop_index(op.f('ix_photos_uploaded_by'), table_name='photos')
    op.drop_index(op.f('ix_photos_organization_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_is_deleted'), table_name='photos')
    op.drop_index(op.f('ix_photos_class_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_category_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_order_line_items_stripe_price_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_organization_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_order_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_is_deleted'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_enrollment_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_discount_code_id'), table_name='order_line_items')
    op.drop_table('order_line_items')
    op.drop_index(op.f('ix_discount_code_usage_user_id'), table_name='discount_code_usage')
    op.drop_index(op.f('ix_discount_code_usage_discount_code_id'), table_name='discount_code_usage')
    op.drop_index(op.f('ix_discount_code_usage_class_id'), table_name='discount_code_usage')
    op.drop_table('discount_code_usage')
    op.drop_index(op.f('ix_checkins_organization_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_is_deleted'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_enrollment_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_class_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_check_in_date'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_attendances_organization_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_marked_by'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_is_deleted'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_enrollment_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_class_id'), table_name='attendances')
    op.drop_index('idx_attendance_date_enrollment', table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_account_credit_transactions_user_id'), table_name='account_credit_transactions')
    op.drop_index('ix_account_credit_transactions_created_at', table_name='account_credit_transactions')
    op.drop_table('account_credit_transactions')
    op.drop_index(op.f('ix_waiver_acceptances_waiver_template_id'), table_name='waiver_acceptances')
    op.drop_index(op.f('ix_waiver_acceptances_user_id'), table_name='waiver_acceptances')
    op.drop_index(op.f('ix_waiver_acceptances_organization_id'), table_name='waiver_acceptances')
    op.drop_index(op.f('ix_waiver_acceptances_is_deleted'), table_name='waiver_acceptances')
    op.drop_table('waiver_acceptances')
    op.drop_index(op.f('ix_scholarships_user_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_organization_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_is_deleted'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_class_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_child_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_approved_by_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_photo_categories_organization_id'), table_name='photo_categories')
    op.drop_index(op.f('ix_photo_categories_is_deleted'), table_name='photo_categories')
    op.drop_index(op.f('ix_photo_categories_class_id'), table_name='photo_categories')
    op.drop_table('photo_categories')
    op.drop_index(op.f('ix_installment_payments_payment_id'), table_name='installment_payments')
    op.drop_index(op.f('ix_installment_payments_organization_id'), table_name='installment_payments')
    op.drop_index(op.f('ix_installment_payments_is_deleted'), table_name='installment_payments')
    op.drop_index(op.f('ix_installment_payments_installment_plan_id'), table_name='installment_payments')
    op.drop_table('installment_payments')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_index(op.f('ix_events_class_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_enrollments_waitlist_priority'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_waitlist_order_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_stripe_subscription_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_organization_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_is_deleted'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_class_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_claim_window_expires_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_child_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_discount_codes_organization_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_is_deleted'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_created_by_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_applies_to_program_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_applies_to_class_id'), table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_index(op.f('ix_announcement_targets_organization_id'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_is_deleted'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_class_id'), table_name='announcement_targets')
    op.drop_index(op.f('ix_announcement_targets_announcement_id'), table_name='announcement_targets')
    op.drop_table('announcement_targets')
    op.drop_index(op.f('ix_waiver_templates_organization_id'), table_name='waiver_templates')
    op.drop_index(op.f('ix_waiver_templates_is_deleted'), table_name='waiver_templates')
    op.drop_index(op.f('ix_waiver_templates_applies_to_school_id'), table_name='waiver_templates')
    op.drop_index(op.f('ix_waiver_templates_applies_to_program_id'), table_name='waiver_templates')
    op.drop_table('waiver_templates')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_refund_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_refund_approved_by_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_next_retry_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_is_deleted'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_installment_plans_user_id'), table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_organization_id'), table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_order_id'), table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_is_deleted'), table_name='installment_plans')
    op.drop_table('installment_plans')
    op.drop_index(op.f('ix_emergency_contacts_organization_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_is_deleted'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_child_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_classes_stripe_product_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_program_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_organization_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_is_deleted'), table_name='classes')
    op.drop_index(op.f('ix_classes_coach_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_area_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_announcement_attachments_organization_id'), table_name='announcement_attachments')
    op.drop_index(op.f('ix_announcement_attachments_is_deleted'), table_name='announcement_attachments')
    op.drop_index(op.f('ix_announcement_attachments_announcement_id'), table_name='announcement_attachments')
    op.drop_table('announcement_attachments')
    op.drop_index(op.f('ix_schools_organization_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_is_deleted'), table_name='schools')
    op.drop_index(op.f('ix_schools_area_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_organization_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_organization_id'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_is_deleted'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stripe_payment_intent_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_organization_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_deleted'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_children_user_id'), table_name='children')
    op.drop_index(op.f('ix_children_organization_id'), table_name='children')
    op.drop_index(op.f('ix_children_is_deleted'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_announcements_organization_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_deleted'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_author_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_organization_email', table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_programs_organization_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_deleted'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_badges_organization_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_is_deleted'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_areas_organization_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_is_deleted'), table_name='areas')
    op.drop_table('areas')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
