"""add_class_ledger_code_image_url_rename_staff_to_coach

Revision ID: e140a2f5a724
Revises: 3e1c72b3c0af
Create Date: 2025-11-24 13:13:41.420446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e140a2f5a724'
down_revision: Union[str, Sequence[str], None] = '3e1c72b3c0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('ledger_code', sa.String(length=50), nullable=True))
    op.add_column('classes', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'image_url')
    op.drop_column('classes', 'ledger_code')
    # ### end Alembic commands ###
